name: venv_loadinsight
dependencies:
  - python=3.7.3
  - pandas
  - numpy
  - matplotlib
  - pip
  - pip:
    - boto3
    - requests
    - Pillow
    - awscli
    - Django==2.2.6
    - djangorestframework==3.10.3
    - django-background-tasks==1.2.5
    - django-templated-mail==1.1.1
    - djoser==2.0.3
    - djet==0.2.2
    - django-background-tasks
    - dj-database-url==0.5.0
    - psycopg2==2.8.4
